services:
  rule-set-syncer:
    container_name: rule-set-syncer
    image: mishkatik/rule-set-syncer:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./sources.json:/usr/src/app/sources.json:ro
